basePath: /mta-hosting-optimizer/
definitions:
  controllers.ResUnusedIpHost:
    properties:
      host:
        type: string
    type: object
info:
  contact:
    email: sahil.kukkar99@gmail.com
    name: API Support
  description: Swagger API for mta-hosting-optimizer Project.
  license:
    name: SAHIL
  title: mta-hosting-optimizer Swagger API
  version: "1.0"
paths:
  /v1/listunusedhost:
    get:
      parameters:
      - description: threshhold
        in: query
        name: threshhold
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controllers.ResUnusedIpHost'
      summary: GetInefficientHosts get unused hosts on threshold
swagger: "2.0"
